set autotrace off timing off
SET VERIFY OFF
--DEFINE SIFUS=USR_SIAFI_OLD

--alter session set current_schema=usr_sipro;

/*
ALTER SESSION SET NLS_SORT='BINARY'
/
ALTER SESSION SET NLS_COMP='BINARY'
/

ALTER SESSION SET NLS_SORT='WEST_EUROPEAN'
/
ALTER SESSION SET NLS_COMP='ANSI'
/
*/

--CREATE INDEX USR_FOLHACD.IX_FFI_BENE_FF_RUBR
--ON  USR_FOLHACD.fichafinanceiraitem(idebeneficiario, idefichafinanceira,iderubrica)
--TABLESPACE TBSI_FOLHACD
--/

ALTER SESSION SET OPTIMIZER_FEATURES_ENABLE='11.2.0.2';
ALTER SESSION SET OPTIMIZER_FEATURES_ENABLE='11.2.0.2';
alter session enable parallel dml;

EXPLAIN PLAN SET STATEMENT_ID='&1.' INTO sys.plan_table$ FOR
INSERT /*+ PARALLEL */ INTO USR_DW_CONLE.STG_TRAMITE_SOLICITACAO 
SELECT 
   UPPER(T6.TXDESCRICAO) SITUACAO
  ,T1.CODSOLICITACAO
  ,T1.SEQ, T2.DTINICIO, T1.DTFIM, T1.DTFIM - T2.DTINICIO DURACAO
  , T1.NOMATIVIDADE,T1.NUPONTORESPONSAVEL, UPPER(SUBSTR(T5.NMFUNCIONARIO, 1, 30)) 
FROM 
(
  SELECT ALL ROWNUM SEQ, R2.*
  FROM 
  (
    SELECT CODSOLICITACAO, NULL DTINICIO, DTFIMATIVIDADE DTFIM, NOMATIVIDADE,NUPONTORESPONSAVEL 
    FROM USR_COLEG.DRESPONSAVELETAPA@LOC_DW_CONLE WHERE CODSOLICITACAO = :B1 ORDER BY DTFIMATIVIDADE
  ) R2 ORDER BY DTFIM 
) T1 
INNER JOIN 
(
  SELECT /*+ PARALLEL */ ALL R1.* 
  FROM 
  (              
     SELECT ALL 
       1 SEQ, COSOLICITACAO CODSOLICITACAO,
       DTENTRADA DTINICIO 
       FROM USR_COLEG.DSOLICITACAO@LOC_DW_CONLE 
       WHERE COSOLICITACAO = :B1 
     UNION 
     SELECT ALL ROWNUM + 1 SEQ,
        CODSOLICITACAO, DTINICIO 
     FROM 
     (
        SELECT ALL CODSOLICITACAO, DTFIMATIVIDADE DTINICIO 
        FROM USR_COLEG.DRESPONSAVELETAPA@LOC_DW_CONLE 
        WHERE CODSOLICITACAO = :B1 ORDER BY DTFIMATIVIDADE 
     ) ORDER BY DTINICIO
  ) R1 
) T2 ON T1.CODSOLICITACAO = T2.CODSOLICITACAO AND T1.SEQ = T2.SEQ 
INNER JOIN USR_COLEG.DFUNCIONARIO@LOC_DW_CONLE T5 ON T5.NUPONTO = T1.NUPONTORESPONSAVEL 
INNER JOIN USR_COLEG.AESTADOSOLICITACAO@LOC_DW_CONLE T6 ON :B2 = T6.COESTADO 
ORDER BY 2,3
/

