set autotrace off timing off
SET VERIFY OFF
--DEFINE SIFUS=USR_SIAFI_OLD

--alter session set current_schema=usr_folhacd;

/*
ALTER SESSION SET NLS_SORT='BINARY'
/
ALTER SESSION SET NLS_COMP='BINARY'
/

ALTER SESSION SET NLS_SORT='WEST_EUROPEAN'
/
ALTER SESSION SET NLS_COMP='ANSI'
/
*/

--CREATE INDEX USR_FOLHACD.IX_FFI_BENE_FF_RUBR
--ON  USR_FOLHACD.fichafinanceiraitem(idebeneficiario, idefichafinanceira,iderubrica)
--TABLESPACE TBSI_FOLHACD
--/

--ALTER SESSION SET OPTIMIZER_FEATURES_ENABLE='12.1.0.2';
--ALTER SESSION SET OPTIMIZER_FEATURES_ENABLE='11.2.0.2';
--alter session enable parallel dml;

EXPLAIN PLAN SET STATEMENT_ID='&1.' INTO sys.plan_table$ FOR
SELECT
USR_DW_RH.DIMSERVIDOR.NUMPONTO,
USR_DW_RH.DIMSERVIDOR.NOMSERVIDOR,
( CASE
when  USR_DW_RH.DIMLOTACAO.NOMNIVEL6 in
(
'DEPARTAMENTO DE MATERIAL E PATRIMONIO',
'DEPARTAMENTO DE RELAÇÕES PÚBLICAS E DIVULGAÇÃO',
'DEPARTAMENTO DE MÍDIAS INTEGRADAS',
'DEPARTAMENTO DE COMISSÕES',
'CENTRO DE INFORMÁTICA',
'CENTRO DE FORMAÇÃO,TREIN.APERFEIÇOAMENTO',
'DEPARTAMENTO DE PESSOAL',
'DEPARTAMENTO TÉCNICO',
'DEPARTAMENTO DE TAQUIG. REVIS. E REDAÇÃO',
'DEPARTAMENTO MÉDICO',
'CONSULTORIA LEGISLATIVA',
'CONSULTORIA DE ORÇAMENTO FISC FINANCEIRA',
'DEP. DE FINANÇAS, ORÇ. E CONTABILIDADE',
'COORDENAÇÃO DE TRANSPORTES',
'DIRETORIA DE RECURSOS HUMANOS',
'SECRETARIA EXECUTIVA DO PRÓ-SAÚDE',
'COORDENAÇÃO DE COMUNICAÇÕES',
'CENTRO DE DOCUMENTAÇÃO E INFORMAÇÃO') Then USR_DW_RH.DIMLOTACAO.NOMNIVEL6
when USR_DW_RH.DIMLOTACAO.NOMNIVEL5 in
(
'DIRETORIA DE RECURSOS HUMANOS',
'PROCURADORIA PARLAMENTAR',
'OUVIDORIA PARLAMENTAR',
'COORDENAÇÃO DE HABITAÇÃO',
'DEPARTAMENTO DE POLÍCIA LEGISLATIVA',
'DIRETORIA ADMINISTRATIVA',
'ASSESSORIA DE PROJETOS E GESTÃO',
'DEPARTAMENTO DE APOIO PARLAMENTAR',
'ASSESSORIA TÉCNICA DA DG',
'DIRETORIA LEGISLATIVA',
'SECRETARIA DE COMUNICAÇÃO SOCIAL',
'SECRETARIA DA MULHER',
'ASSESSORIA INTERNACIONAL E CERIMONIAL',
'GRUPO DE TRABALHO CONS. LEG. BRASILEIRA'
) Then
USR_DW_RH.DIMLOTACAO.NOMNIVEL5
when USR_DW_RH.DIMLOTACAO.NOMNIVEL4 in
(
'GABINETE DOS SUPLENTES DOS SECRETÁRIOS',
'GABINETE DO QUARTO-SECRETÁRIO',
'GABINETE DO TERCEIRO-SECRETÁRIO',
'GABINETE DO SEGUNDO-SECRETÁRIO',
'GABINETE DO SEGUNDO-SECRETÁRIO',
'GABINETE DO PRIMEIRO-SECRETÁRIO',
'GABINETE DO PRIMEIRO VICE-PRESIDENTE',
'GABINETE DO SEGUNDO VICE-PRESIDENTE',
'GABINETE DO PRESIDENTE',
'CORREGEDORIA PARLAMENTAR',
'DIRETORIA-GERAL',
'SECRETARIA-GERAL DA MESA',
'SECRETARIA DE CONTROLE INTERNO',
'CENTRO DE ESTUDOS E DEBATES ESTRATÉGICOS DA CÂMARA DOS DEPUTADOS',
'CONSELHO DE ÉTICA E DECORO PARLAMENTAR'
) Then USR_DW_RH.DIMLOTACAO.NOMNIVEL4
When  USR_DW_RH.DIMLOTACAO.NOMNIVEL3 in
('LIDERANÇA DA MINORIA',
'LIDERANÇA DO DEMOCRATAS',
'LIDERANÇA DO GOVERNO NA CÂMARA',
'LIDERANÇA DO GOVERNO NO CONGRESSO',
'LIDERANÇA DO PC DO B',
'LIDERANÇA DO PDT',
'LIDERANÇA DO PMDB',
'LIDERANÇA DO PP',
'LIDERANÇA DO PPS',
'LIDERANÇA DO PR',
'LIDERANÇA DO PRB',
'LIDERANÇA DO PSDB',
'LIDERANÇA DO PT',
'LIDERANÇA DO PTB',
'LIDERANÇA DO PV',
'LIDERANÇA DO PSC',
'LIDERANÇA DO PSB',
'LIDERANÇA DO PSD',
'A DISPOSIÇÃO DO SENADO FEDERAL',
'A DISPOSIÇAO DE OUTRO ORGAO PUBLICO',
'EXERCÍCIO PROVISÓRIO OUTRO ÓRGÃO PÚBLICO',
'LIDERANÇA DO PARTIDO REPUBLICANO DA ORDEM SOCIAL',
'LIDERANÇA DO SOLIDARIEDADE'
)
Then USR_DW_RH.DIMLOTACAO.NOMNIVEL3
When  USR_DW_RH.DIMLOTACAO.NOMNIVEL2 in
(
'DEPARTAMENTO DE PESSOAL (AFASTADO)'
)
Then USR_DW_RH.DIMLOTACAO.NOMNIVEL2
When USR_DW_RH.DIMLOTACAO.SIGLOTACAO= 'N/A' Then 'NÃO INFORMADO'
Else 'OUTROS'
END ),
( CASE
when  USR_DW_RH.DIMLOTACAO.NOMNIVEL6 in
(
'DEPARTAMENTO DE MATERIAL E PATRIMONIO',
'DEPARTAMENTO DE RELAÇÕES PÚBLICAS E DIVULGAÇÃO',
'DEPARTAMENTO DE MÍDIAS INTEGRADAS',
'DEPARTAMENTO DE COMISSÕES',
'CENTRO DE INFORMÁTICA',
'CENTRO DE FORMAÇÃO,TREIN.APERFEIÇOAMENTO',
'DEPARTAMENTO DE PESSOAL',
'DEPARTAMENTO TÉCNICO',
'DEPARTAMENTO DE TAQUIG. REVIS. E REDAÇÃO',
'DEPARTAMENTO MÉDICO',
'CONSULTORIA LEGISLATIVA',
'CONSULTORIA DE ORÇAMENTO FISC FINANCEIRA',
'DEP. DE FINANÇAS, ORÇ. E CONTABILIDADE',
'COORDENAÇÃO DE TRANSPORTES',
'DIRETORIA DE RECURSOS HUMANOS',
'SECRETARIA EXECUTIVA DO PRÓ-SAÚDE',
'COORDENAÇÃO DE COMUNICAÇÕES',
'CENTRO DE DOCUMENTAÇÃO E INFORMAÇÃO') Then USR_DW_RH.DIMLOTACAO.SIGNIVEL6
when USR_DW_RH.DIMLOTACAO.NOMNIVEL5 in
(
'DIRETORIA DE RECURSOS HUMANOS',
'PROCURADORIA PARLAMENTAR',
'OUVIDORIA PARLAMENTAR',
'COORDENAÇÃO DE HABITAÇÃO',
'DEPARTAMENTO DE POLÍCIA LEGISLATIVA',
'DIRETORIA ADMINISTRATIVA',
'ASSESSORIA DE PROJETOS E GESTÃO',
'DEPARTAMENTO DE APOIO PARLAMENTAR',
'ASSESSORIA TÉCNICA DA DG',
'DIRETORIA LEGISLATIVA',
'SECRETARIA DE COMUNICAÇÃO SOCIAL',
'SECRETARIA DA MULHER',
'ASSESSORIA INTERNACIONAL E CERIMONIAL',
'GRUPO DE TRABALHO CONS. LEG. BRASILEIRA'
)
Then USR_DW_RH.DIMLOTACAO.SIGNIVEL5
when USR_DW_RH.DIMLOTACAO.NOMNIVEL4 in
(
'GABINETE DOS SUPLENTES DOS SECRETÁRIOS',
'GABINETE DO QUARTO-SECRETÁRIO',
'GABINETE DO TERCEIRO-SECRETÁRIO',
'GABINETE DO SEGUNDO-SECRETÁRIO',
'GABINETE DO SEGUNDO-SECRETÁRIO',
'GABINETE DO PRIMEIRO-SECRETÁRIO',
'GABINETE DO PRIMEIRO VICE-PRESIDENTE',
'GABINETE DO SEGUNDO VICE-PRESIDENTE',
'GABINETE DO PRESIDENTE',
'CORREGEDORIA PARLAMENTAR',
'DIRETORIA-GERAL',
'SECRETARIA-GERAL DA MESA',
'SECRETARIA DE CONTROLE INTERNO',
'CENTRO DE ESTUDOS E DEBATES ESTRATÉGICOS DA CÂMARA DOS DEPUTADOS',
'CONSELHO DE ÉTICA E DECORO PARLAMENTAR'
) Then USR_DW_RH.DIMLOTACAO.SIGNIVEL4
When  USR_DW_RH.DIMLOTACAO.NOMNIVEL3 in
('LIDERANÇA DA MINORIA',
'LIDERANÇA DO DEMOCRATAS',
'LIDERANÇA DO GOVERNO NA CÂMARA',
'LIDERANÇA DO GOVERNO NO CONGRESSO',
'LIDERANÇA DO PC DO B',
'LIDERANÇA DO PDT',
'LIDERANÇA DO PMDB',
'LIDERANÇA DO PP',
'LIDERANÇA DO PPS',
'LIDERANÇA DO PR',
'LIDERANÇA DO PRB',
'LIDERANÇA DO PSDB',
'LIDERANÇA DO PT',
'LIDERANÇA DO PTB',
'LIDERANÇA DO PV',
'LIDERANÇA DO PSC',
'LIDERANÇA DO PSB',
'LIDERANÇA DO PSD',
'A DISPOSIÇÃO DO SENADO FEDERAL',
'A DISPOSIÇAO DE OUTRO ORGAO PUBLICO',
'EXERCÍCIO PROVISÓRIO OUTRO ÓRGÃO PÚBLICO',
'LIDERANÇA DO PARTIDO REPUBLICANO DA ORDEM SOCIAL',
'LIDERANÇA DO SOLIDARIEDADE'
)
Then USR_DW_RH.DIMLOTACAO.SIGNIVEL3
When  USR_DW_RH.DIMLOTACAO.NOMNIVEL2 in
(
'DEPARTAMENTO DE PESSOAL (AFASTADO)'
)
Then USR_DW_RH.DIMLOTACAO.SIGNIVEL2
When USR_DW_RH.DIMLOTACAO.SIGLOTACAO= 'N/A' Then 'NÃO INFORMADO'
Else 'OUTROS'
END ),
USR_DW_RH.DIMLOTACAO.NOMLOTACAO,
USR_DW_RH.DIMLOTACAO.SIGLOTACAO,
USR_DW_RH.DIMLOTACAO.SIGNIVEL1,
USR_DW_RH.DIMTIPOAFASTAMENTO.DESCAFASTAMENTO,
USR_DW_CORPORATIVO.DIMTEMPO.CODANO,
USR_DW_CORPORATIVO.DIMTEMPO.CODMES,
sum (USR_DW_RH.FTAFASTAMENTOSDIARIO.QTD_DIAS_AFASTAMENTO),
USR_DW_RH.DIMTIPOAFASTAMENTO.TEXUSADOATUALMENTE,
USR_DW_RH.DIMSERVIDOR.INDSEXO,
USR_DW_RH.DIMSERVIDOR.IDESERVIDOR,
USR_DW_RH.SUBDIMGRUPO.NOMGRUPO
FROM USR_DW_RH.FTAFASTAMENTOSDIARIO 
JOIN USR_DW_RH.DIMTIPOAFASTAMENTO ON ( USR_DW_RH.DIMTIPOAFASTAMENTO.IDETIPOAFASTAMENTO  = USR_DW_RH.FTAFASTAMENTOSDIARIO.IDETIPOAFASTAMENTO)
JOIN USR_DW_RH.DIMLOTACAO ON (USR_DW_RH.DIMLOTACAO.IDELOTACAO=USR_DW_RH.FTAFASTAMENTOSDIARIO.IDELOTACAO)
JOIN USR_DW_CORPORATIVO.DIMTEMPO ON ( USR_DW_CORPORATIVO.DIMTEMPO.IDETEMPO=USR_DW_RH.FTAFASTAMENTOSDIARIO.IDETEMPO )
JOIN USR_DW_RH.DIMSERVIDOR ON  (USR_DW_RH.DIMSERVIDOR.IDESERVIDOR=USR_DW_RH.FTAFASTAMENTOSDIARIO.IDESERVIDOR )
JOIN USR_DW_RH.SUBDIMGRUPO on (USR_DW_RH.SUBDIMGRUPO.IDEGRUPO=USR_DW_RH.DIMSERVIDOR.IDEGRUPO  )
WHERE USR_DW_CORPORATIVO.DIMTEMPO.CODANO  >  2009
AND USR_DW_RH.DIMTIPOAFASTAMENTO.TEXUSADOATUALMENTE  =  'Sim'
GROUP BY
USR_DW_RH.DIMSERVIDOR.NUMPONTO,
USR_DW_RH.DIMSERVIDOR.NOMSERVIDOR,
( CASE
when  USR_DW_RH.DIMLOTACAO.NOMNIVEL6 in
(
'DEPARTAMENTO DE MATERIAL E PATRIMONIO',
'DEPARTAMENTO DE RELAÇÕES PÚBLICAS E DIVULGAÇÃO',
'DEPARTAMENTO DE MÍDIAS INTEGRADAS',
'DEPARTAMENTO DE COMISSÕES',
'CENTRO DE INFORMÁTICA',
'CENTRO DE FORMAÇÃO,TREIN.APERFEIÇOAMENTO',
'DEPARTAMENTO DE PESSOAL',
'DEPARTAMENTO TÉCNICO',
'DEPARTAMENTO DE TAQUIG. REVIS. E REDAÇÃO',
'DEPARTAMENTO MÉDICO',
'CONSULTORIA LEGISLATIVA',
'CONSULTORIA DE ORÇAMENTO FISC FINANCEIRA',
'DEP. DE FINANÇAS, ORÇ. E CONTABILIDADE',
'COORDENAÇÃO DE TRANSPORTES',
'DIRETORIA DE RECURSOS HUMANOS',
'SECRETARIA EXECUTIVA DO PRÓ-SAÚDE',
'COORDENAÇÃO DE COMUNICAÇÕES',
'CENTRO DE DOCUMENTAÇÃO E INFORMAÇÃO') Then USR_DW_RH.DIMLOTACAO.NOMNIVEL6
when USR_DW_RH.DIMLOTACAO.NOMNIVEL5 in
(
'DIRETORIA DE RECURSOS HUMANOS',
'PROCURADORIA PARLAMENTAR',
'OUVIDORIA PARLAMENTAR',
'COORDENAÇÃO DE HABITAÇÃO',
'DEPARTAMENTO DE POLÍCIA LEGISLATIVA',
'DIRETORIA ADMINISTRATIVA',
'ASSESSORIA DE PROJETOS E GESTÃO',
'DEPARTAMENTO DE APOIO PARLAMENTAR',
'ASSESSORIA TÉCNICA DA DG',
'DIRETORIA LEGISLATIVA',
'SECRETARIA DE COMUNICAÇÃO SOCIAL',
'SECRETARIA DA MULHER',
'ASSESSORIA INTERNACIONAL E CERIMONIAL',
'GRUPO DE TRABALHO CONS. LEG. BRASILEIRA'
) Then
USR_DW_RH.DIMLOTACAO.NOMNIVEL5
when USR_DW_RH.DIMLOTACAO.NOMNIVEL4 in
(
'GABINETE DOS SUPLENTES DOS SECRETÁRIOS',
'GABINETE DO QUARTO-SECRETÁRIO',
'GABINETE DO TERCEIRO-SECRETÁRIO',
'GABINETE DO SEGUNDO-SECRETÁRIO',
'GABINETE DO SEGUNDO-SECRETÁRIO',
'GABINETE DO PRIMEIRO-SECRETÁRIO',
'GABINETE DO PRIMEIRO VICE-PRESIDENTE',
'GABINETE DO SEGUNDO VICE-PRESIDENTE',
'GABINETE DO PRESIDENTE',
'CORREGEDORIA PARLAMENTAR',
'DIRETORIA-GERAL',
'SECRETARIA-GERAL DA MESA',
'SECRETARIA DE CONTROLE INTERNO',
'CENTRO DE ESTUDOS E DEBATES ESTRATÉGICOS DA CÂMARA DOS DEPUTADOS',
'CONSELHO DE ÉTICA E DECORO PARLAMENTAR'
) Then USR_DW_RH.DIMLOTACAO.NOMNIVEL4
When  USR_DW_RH.DIMLOTACAO.NOMNIVEL3 in
('LIDERANÇA DA MINORIA',
'LIDERANÇA DO DEMOCRATAS',
'LIDERANÇA DO GOVERNO NA CÂMARA',
'LIDERANÇA DO GOVERNO NO CONGRESSO',
'LIDERANÇA DO PC DO B',
'LIDERANÇA DO PDT',
'LIDERANÇA DO PMDB',
'LIDERANÇA DO PP',
'LIDERANÇA DO PPS',
'LIDERANÇA DO PR',
'LIDERANÇA DO PRB',
'LIDERANÇA DO PSDB',
'LIDERANÇA DO PT',
'LIDERANÇA DO PTB',
'LIDERANÇA DO PV',
'LIDERANÇA DO PSC',
'LIDERANÇA DO PSB',
'LIDERANÇA DO PSD',
'A DISPOSIÇÃO DO SENADO FEDERAL',
'A DISPOSIÇAO DE OUTRO ORGAO PUBLICO',
'EXERCÍCIO PROVISÓRIO OUTRO ÓRGÃO PÚBLICO',
'LIDERANÇA DO PARTIDO REPUBLICANO DA ORDEM SOCIAL',
'LIDERANÇA DO SOLIDARIEDADE'
)
Then USR_DW_RH.DIMLOTACAO.NOMNIVEL3
When  USR_DW_RH.DIMLOTACAO.NOMNIVEL2 in
(
'DEPARTAMENTO DE PESSOAL (AFASTADO)'
)
Then USR_DW_RH.DIMLOTACAO.NOMNIVEL2
When USR_DW_RH.DIMLOTACAO.SIGLOTACAO= 'N/A' Then 'NÃO INFORMADO'
Else 'OUTROS'
END ),
( CASE
when  USR_DW_RH.DIMLOTACAO.NOMNIVEL6 in
(
'DEPARTAMENTO DE MATERIAL E PATRIMONIO',
'DEPARTAMENTO DE RELAÇÕES PÚBLICAS E DIVULGAÇÃO',
'DEPARTAMENTO DE MÍDIAS INTEGRADAS',
'DEPARTAMENTO DE COMISSÕES',
'CENTRO DE INFORMÁTICA',
'CENTRO DE FORMAÇÃO,TREIN.APERFEIÇOAMENTO',
'DEPARTAMENTO DE PESSOAL',
'DEPARTAMENTO TÉCNICO',
'DEPARTAMENTO DE TAQUIG. REVIS. E REDAÇÃO',
'DEPARTAMENTO MÉDICO',
'CONSULTORIA LEGISLATIVA',
'CONSULTORIA DE ORÇAMENTO FISC FINANCEIRA',
'DEP. DE FINANÇAS, ORÇ. E CONTABILIDADE',
'COORDENAÇÃO DE TRANSPORTES',
'DIRETORIA DE RECURSOS HUMANOS',
'SECRETARIA EXECUTIVA DO PRÓ-SAÚDE',
'COORDENAÇÃO DE COMUNICAÇÕES',
'CENTRO DE DOCUMENTAÇÃO E INFORMAÇÃO') Then USR_DW_RH.DIMLOTACAO.SIGNIVEL6
when USR_DW_RH.DIMLOTACAO.NOMNIVEL5 in
(
'DIRETORIA DE RECURSOS HUMANOS',
'PROCURADORIA PARLAMENTAR',
'OUVIDORIA PARLAMENTAR',
'COORDENAÇÃO DE HABITAÇÃO',
'DEPARTAMENTO DE POLÍCIA LEGISLATIVA',
'DIRETORIA ADMINISTRATIVA',
'ASSESSORIA DE PROJETOS E GESTÃO',
'DEPARTAMENTO DE APOIO PARLAMENTAR',
'ASSESSORIA TÉCNICA DA DG',
'DIRETORIA LEGISLATIVA',
'SECRETARIA DE COMUNICAÇÃO SOCIAL',
'SECRETARIA DA MULHER',
'ASSESSORIA INTERNACIONAL E CERIMONIAL',
'GRUPO DE TRABALHO CONS. LEG. BRASILEIRA'
)
Then USR_DW_RH.DIMLOTACAO.SIGNIVEL5
when USR_DW_RH.DIMLOTACAO.NOMNIVEL4 in
(
'GABINETE DOS SUPLENTES DOS SECRETÁRIOS',
'GABINETE DO QUARTO-SECRETÁRIO',
'GABINETE DO TERCEIRO-SECRETÁRIO',
'GABINETE DO SEGUNDO-SECRETÁRIO',
'GABINETE DO SEGUNDO-SECRETÁRIO',
'GABINETE DO PRIMEIRO-SECRETÁRIO',
'GABINETE DO PRIMEIRO VICE-PRESIDENTE',
'GABINETE DO SEGUNDO VICE-PRESIDENTE',
'GABINETE DO PRESIDENTE',
'CORREGEDORIA PARLAMENTAR',
'DIRETORIA-GERAL',
'SECRETARIA-GERAL DA MESA',
'SECRETARIA DE CONTROLE INTERNO',
'CENTRO DE ESTUDOS E DEBATES ESTRATÉGICOS DA CÂMARA DOS DEPUTADOS',
'CONSELHO DE ÉTICA E DECORO PARLAMENTAR'
) Then USR_DW_RH.DIMLOTACAO.SIGNIVEL4
When  USR_DW_RH.DIMLOTACAO.NOMNIVEL3 in
('LIDERANÇA DA MINORIA',
'LIDERANÇA DO DEMOCRATAS',
'LIDERANÇA DO GOVERNO NA CÂMARA',
'LIDERANÇA DO GOVERNO NO CONGRESSO',
'LIDERANÇA DO PC DO B',
'LIDERANÇA DO PDT',
'LIDERANÇA DO PMDB',
'LIDERANÇA DO PP',
'LIDERANÇA DO PPS',
'LIDERANÇA DO PR',
'LIDERANÇA DO PRB',
'LIDERANÇA DO PSDB',
'LIDERANÇA DO PT',
'LIDERANÇA DO PTB',
'LIDERANÇA DO PV',
'LIDERANÇA DO PSC',
'LIDERANÇA DO PSB',
'LIDERANÇA DO PSD',
'A DISPOSIÇÃO DO SENADO FEDERAL',
'A DISPOSIÇAO DE OUTRO ORGAO PUBLICO',
'EXERCÍCIO PROVISÓRIO OUTRO ÓRGÃO PÚBLICO',
'LIDERANÇA DO PARTIDO REPUBLICANO DA ORDEM SOCIAL',
'LIDERANÇA DO SOLIDARIEDADE'
)
Then USR_DW_RH.DIMLOTACAO.SIGNIVEL3
When  USR_DW_RH.DIMLOTACAO.NOMNIVEL2 in
(
'DEPARTAMENTO DE PESSOAL (AFASTADO)'
)
Then USR_DW_RH.DIMLOTACAO.SIGNIVEL2
When USR_DW_RH.DIMLOTACAO.SIGLOTACAO= 'N/A' Then 'NÃO INFORMADO'
Else 'OUTROS'
END ),
USR_DW_RH.DIMLOTACAO.NOMLOTACAO,
USR_DW_RH.DIMLOTACAO.SIGLOTACAO,
USR_DW_RH.DIMLOTACAO.SIGNIVEL1,
USR_DW_RH.DIMTIPOAFASTAMENTO.DESCAFASTAMENTO,
USR_DW_CORPORATIVO.DIMTEMPO.CODANO,
USR_DW_CORPORATIVO.DIMTEMPO.CODMES,
USR_DW_RH.DIMTIPOAFASTAMENTO.TEXUSADOATUALMENTE,
USR_DW_RH.DIMSERVIDOR.INDSEXO,
USR_DW_RH.DIMSERVIDOR.IDESERVIDOR,
USR_DW_RH.SUBDIMGRUPO.NOMGRUPO
/
