SET TERMOUT OFF FEEDBACK OFF VERIFY OFF PAGES 500 LINES 200 UNDERLINE '~'

COL PLAN_HASH_VALUE       FORMAT 99999999999    JUST R 

DEFINE P1=&1.

@detalhesql &P1

SET VERIFY OFF FEED OFF

--DEBUG: TO FORCE A SPECIFIC COPY
--DEFINE P_ADDR='00000001377C95E0'

@getplan&p_versao. &p_hash. &p_addr.

ROLLBACK;

PROMPT

UNDEFINE P_SQL_ID P_HASH P_ADDR P_VERSAO


SET PAGES 100 FEEDBACK 6 VERIFY ON UNDERLINE '-'

