SET DEFINE ON

DEFINE P_TBS="&1."
DEFINE P_OWNER="&2."
DEFINE P_SEG="&3."
DEFINE P_AGRUPAR='NO'
DEFINE P_RESUMIR='NO'
DEFINE P_SORT='TABLE'
DEFINE P_SORT='SIZE'
DEFINE P_MEGAS=0
DEFINE P_PCTOCUP=100

@@monit.segments.sql &P_AGRUPAR. &P_RESUMIR. &P_SORT. &P_TBS. &P_OWNER. "&P_SEG." &P_PCTOCUP. &P_MEGAS.

rem @@do.monitsegs.sql

PROMPT
PROMPT Para obter o resumo dos objetos use @monitsegs &p_tbs. &p_owner. &p_seg.
PROMPT Para obter o resumo agrupado por tabela objetos use @monitsegss &p_tbs. &p_owner. &p_seg.
PROMPT

UNDEFINE 1
UNDEFINE 2
UNDEFINE 3
UNDEFINE P_TBS
UNDEFINE P_OWNER
UNDEFINE P_SEG
UNDEFINE P_AGRUPAR
UNDEFINE P_RESUMIR
UNDEFINE P_SORT
UNDEFINE P_PCTOCUP
UNDEFINE P_MEGAS

SET SERVEROUT OFF VERIFY ON FEED ON

