SET LINES 150
COLUMN NAME FOR A11 HEAD DB_NAME
COLUMN UPGRADE_DATE FORMAT A21 head UPGRADE_DATE
COLUMN ACTION FORMAT A11
COLUMN NAMESPACE FORMAT A11
COLUMN VERSION FORMAT A11
COLUMN COMMENTS FORMAT A80
 
SELECT BANNER_FULL FROM V$VERSION
/

SELECT 
	NAME 
, TO_CHAR(ACTION_TIME, 'DD/MM/YYYY HH24:MI') AS UPGRADE_DATE
, ACTION
, NAMESPACE
, VERSION
, COMMENTS
FROM   V$DATABASE, SYS.REGISTRY$HISTORY WHERE ACTION LIKE '%UPGRADE%'
ORDER BY ACTION_TIME
/
